<script setup>
import { ref } from 'vue';
import CategoryTree from './CategoryTree.vue';
import { loadCatalog } from '../../catalog-state.js';
const props = defineProps({ model: Object, prefix: { type: String, default: 'desktop' } });
const categorySearch = ref('');
function filterTree(items) { const query = categorySearch.value.trim(); if (!query) return items; return items.flatMap((item) => { const children = filterTree(item.children || []); return item.name.includes(query) || children.length ? [{ ...item, children }] : []; }); }
function selected(slug, value) { return (props.model.state.values[slug] || []).includes(String(value)); }
</script>
<template>
    <div class="dc-filters" :aria-busy="model.result.filtersLoading">
        <div class="dc-filter-heading"><h2>انتخاب دقیق‌تر</h2><button type="button" class="dc-text-button" :disabled="!model.chips.value.length" @click="model.clearFilters">پاک‌کردن همه</button></div>
        <section class="dc-filter-group"><h3>مجموعه‌ها</h3><label :for="`${prefix}-category-search`" class="dc-sr-only">جستجوی دسته‌بندی</label><input :id="`${prefix}-category-search`" v-model="categorySearch" type="search" placeholder="جستجوی مجموعه…" /><p v-if="model.catalog.status === 'loading'" role="status">در حال دریافت مجموعه‌ها…</p><div v-else-if="model.catalog.status === 'error'" role="alert"><p>{{ model.catalog.error }}</p><button type="button" class="dc-text-button" @click="loadCatalog({ retry: true })">تلاش مجدد</button></div><template v-else><button type="button" class="dc-all-categories" :aria-pressed="!model.state.category" @click="model.selectCategory('')">همه محصولات</button><CategoryTree :items="filterTree(model.catalog.categories)" :selected="model.state.category" @select="model.selectCategory" /><p v-if="!filterTree(model.catalog.categories).length">مجموعه‌ای پیدا نشد.</p></template></section>
        <p v-if="!model.state.category" class="dc-filter-note">برای دیدن فیلترهای اختصاصی، یک مجموعه انتخاب کنید.</p>
        <div v-if="model.result.filtersLoading" class="dc-facet-loading" role="status" aria-label="در حال دریافت فیلترها"><span class="sf-skeleton" /><span class="sf-skeleton" /></div>
        <div v-if="model.result.filtersError" role="alert" class="dc-filter-note"><p>{{ model.result.filtersError }}</p><button type="button" class="dc-text-button" @click="model.loadFilters">تلاش مجدد</button></div>
        <fieldset v-for="filter in model.result.filters" :key="filter.slug" class="dc-filter-group" :disabled="model.result.filtersLoading"><legend>{{ filter.name }}</legend><div v-if="filter.values?.length" class="dc-filter-options"><button v-for="value in filter.values" :key="String(value.value)" type="button" :aria-pressed="selected(filter.slug, value.value)" :class="{ 'is-selected': selected(filter.slug, value.value) }" @click="model.toggleValue(filter.slug, value.value)"><span v-if="filter.type === 'color' && value.hex_color" class="dc-swatch" :style="{ background: /^#[0-9a-f]{3}([0-9a-f]{3})?$/i.test(value.hex_color) ? value.hex_color : 'transparent' }" aria-hidden="true" /><span>{{ value.label ?? value.value }}</span><span v-if="selected(filter.slug, value.value)" aria-hidden="true">✓</span><small v-if="value.count != null">{{ Number(value.count).toLocaleString('fa-IR') }}</small></button></div><div v-else-if="filter.type === 'boolean'" class="dc-filter-options"><button v-for="option in [{ value: 'true', label: 'بله' }, { value: 'false', label: 'خیر' }]" :key="option.value" type="button" :aria-pressed="selected(filter.slug, option.value)" @click="model.toggleValue(filter.slug, option.value)">{{ option.label }}<span v-if="selected(filter.slug, option.value)" aria-hidden="true"> ✓</span></button></div><label v-else-if="filter.type === 'number' || filter.type === 'text'"><span class="dc-sr-only">{{ filter.name }}</span><input :type="filter.type === 'number' ? 'number' : 'text'" :value="model.state.values[filter.slug]?.[0] || ''" @change="model.setScalar(filter.slug, $event.target.value)" /></label><p v-else class="dc-filter-note">گزینه‌ای در این مجموعه موجود نیست.</p></fieldset>
        <fieldset class="dc-filter-group"><legend>قیمت <small>تومان</small></legend><div class="dc-price-inputs"><label>از<input type="number" min="0" inputmode="numeric" v-model="model.state.priceMin" @change="model.change()" /></label><label>تا<input type="number" min="0" inputmode="numeric" v-model="model.state.priceMax" @change="model.change()" /></label></div></fieldset>
        <label class="dc-stock-control"><input type="checkbox" v-model="model.state.inStock" @change="model.change()" /><span>فقط محصولات موجود</span></label>
    </div>
</template>
